import type { AnswerPostFeedItemDto } from '@/shared/types/api';

export const MOCK_ANONYMOUS_NICKNAMES = [
  '고요한 바다', '따뜻한 햇살', '생각하는 구름', '조용한 파도',
  '빛나는 별', '걷는 바람', '꿈꾸는 달', '은은한 달빛',
  '푸른 하늘', '흐르는 강', '웃는 꽃', '노래하는 새',
  '깊은 숲', '맑은 이슬', '춤추는 나비', '쉬어가는 돌',
  '기다리는 나무', '속삭이는 풀', '흔들리는 갈대', '피어나는 봄',
  '잠드는 저녁', '깨어나는 아침', '빗속의 우산', '모닥불 옆 고양이',
];

export const MOCK_FEED_ITEMS: AnswerPostFeedItemDto[] = [
  {
    answerPostId: 1,
    questionContent: '오늘 하루 중 가장 감사했던 순간은 무엇인가요?',
    description: null,
    answerContent: '아침에 눈을 떴을 때 창문으로 들어오는 햇살이 정말 따뜻했어요. 커피 한 잔을 마시며 그 빛을 바라보고 있으니, 이렇게 평범한 아침이 얼마나 소중한지 새삼 느꼈습니다.',
    postedAt: '2026-03-23T08:30:00',
    anonymousNickname: '따뜻한 햇살',
    liked: false,
    likeCount: 24,
    mine: false,
  },
  {
    answerPostId: 2,
    questionContent: '살면서 가장 용기를 냈던 순간은 언제인가요?',
    description: null,
    answerContent: '대학교를 그만두고 내가 정말 하고 싶은 일을 찾아 나섰을 때요. 주변에서 다들 반대했지만, 그때 내 마음의 소리를 따르지 않았다면 지금의 나는 없었을 거예요.',
    postedAt: '2026-03-22T21:15:00',
    anonymousNickname: '걷는 바람',
    liked: true,
    likeCount: 42,
    mine: false,
  },
  {
    answerPostId: 3,
    questionContent: '요즘 가장 많이 하는 생각은 무엇인가요?',
    description: null,
    answerContent: '시간이 너무 빨리 간다는 생각을 자주 해요. 어제가 월요일이었는데 벌써 주말이고, 3월도 곧 끝나가고... 하루하루를 더 의미 있게 보내고 싶다는 마음이 커요.',
    postedAt: '2026-03-22T19:00:00',
    anonymousNickname: '생각하는 구름',
    liked: false,
    likeCount: 15,
    mine: false,
  },
  {
    answerPostId: 4,
    questionContent: '10년 후의 나에게 하고 싶은 말이 있다면?',
    description: null,
    answerContent: '지금 힘들어도 잘 버티고 있어, 고마워. 그때의 너는 분명 지금보다 더 단단하고 따뜻한 사람이 되어 있을 거야.',
    postedAt: '2026-03-21T22:30:00',
    anonymousNickname: '꿈꾸는 달',
    liked: false,
    likeCount: 38,
    mine: false,
  },
  {
    answerPostId: 5,
    questionContent: '최근에 읽은 책이나 본 영화 중 인상 깊었던 것은?',
    description: null,
    answerContent: '최근에 "아몬드"라는 책을 읽었는데, 감정을 느끼지 못하는 주인공이 세상과 소통하는 법을 배워가는 이야기였어요.',
    postedAt: '2026-03-21T20:00:00',
    anonymousNickname: '깊은 숲',
    liked: true,
    likeCount: 31,
    mine: false,
  },
  {
    answerPostId: 6,
    questionContent: '오늘 가장 행복했던 순간은 무엇인가요?',
    description: null,
    answerContent: '퇴근길에 이어폰으로 좋아하는 노래를 듣는데, 딱 그 순간 바람이 불어왔어요. 노래와 바람이 완벽하게 어울렸고, 그 순간만큼은 세상 모든 걱정이 사라진 것 같았어요.',
    postedAt: '2026-03-21T18:45:00',
    anonymousNickname: '노래하는 새',
    liked: false,
    likeCount: 19,
    mine: false,
  },
  {
    answerPostId: 7,
    questionContent: '어린 시절의 나에게 해주고 싶은 말은?',
    description: null,
    answerContent: '걱정하지 마, 넌 생각보다 잘 해낼 거야. 지금 느끼는 불안함과 두려움은 다 지나가고, 나중에 보면 그때가 가장 순수하고 아름다운 시간이었다는 걸 알게 될 거야.',
    postedAt: '2026-03-20T15:20:00',
    anonymousNickname: '피어나는 봄',
    liked: false,
    likeCount: 55,
    mine: false,
  },
  {
    answerPostId: 8,
    questionContent: '지금 이 순간 가장 듣고 싶은 말은?',
    description: null,
    answerContent: '"충분히 잘하고 있어." 이 말이 제일 듣고 싶어요. 항상 부족하다고 느끼고, 더 잘해야 한다는 압박감 속에 살고 있거든요.',
    postedAt: '2026-03-20T12:00:00',
    anonymousNickname: '고요한 바다',
    liked: true,
    likeCount: 67,
    mine: false,
  },
  {
    answerPostId: 9,
    questionContent: '나만의 스트레스 해소법이 있다면?',
    description: null,
    answerContent: '밤에 혼자 산책하는 거예요. 이어폰 끼고 아무 생각 없이 걷다 보면 복잡했던 머릿속이 정리되는 느낌이에요.',
    postedAt: '2026-03-19T23:00:00',
    anonymousNickname: '빗속의 우산',
    liked: false,
    likeCount: 28,
    mine: false,
  },
  {
    answerPostId: 10,
    questionContent: '나를 가장 잘 표현하는 단어 세 개는?',
    description: null,
    answerContent: '호기심, 따뜻함, 고집. 항상 새로운 것에 관심이 많고, 주변 사람들에게 따뜻하게 대하려 노력하지만, 내가 옳다고 생각하는 것에 대해서는 꽤 고집이 세요.',
    postedAt: '2026-03-19T17:30:00',
    anonymousNickname: '흔들리는 갈대',
    liked: false,
    likeCount: 12,
    mine: false,
  },
  {
    answerPostId: 11,
    questionContent: '가장 최근에 누군가에게 고마움을 느낀 적은?',
    description: null,
    answerContent: '회사에서 실수를 했을 때, 아무 말 없이 옆에서 도와준 동료가 있었어요. "괜찮아, 누구나 그럴 수 있어"라는 한마디가 그날 하루를 버틸 수 있게 해줬어요.',
    postedAt: '2026-03-18T20:15:00',
    anonymousNickname: '웃는 꽃',
    liked: false,
    likeCount: 33,
    mine: false,
  },
  {
    answerPostId: 12,
    questionContent: '지금 당장 떠나고 싶은 곳이 있다면 어디인가요?',
    description: null,
    answerContent: '제주도 바닷가 작은 카페에서 하루 종일 바다를 바라보며 아무것도 하지 않고 싶어요. 핸드폰도 끄고, 그냥 파도 소리만 들으면서.',
    postedAt: '2026-03-18T14:00:00',
    anonymousNickname: '조용한 파도',
    liked: true,
    likeCount: 45,
    mine: false,
  },
  {
    answerPostId: 13,
    questionContent: '오늘 새롭게 알게 된 것이 있나요?',
    description: null,
    answerContent: '고양이가 그르렁거리는 건 기분이 좋을 때만이 아니라 아플 때도 한다는 걸 알게 됐어요. 스스로를 치유하는 행동이래요.',
    postedAt: '2026-03-17T21:00:00',
    anonymousNickname: '모닥불 옆 고양이',
    liked: false,
    likeCount: 22,
    mine: false,
  },
  {
    answerPostId: 14,
    questionContent: '내 삶에서 가장 중요한 가치는 무엇인가요?',
    description: null,
    answerContent: '진정성이요. 남들이 기대하는 모습이 아닌, 있는 그대로의 나로 살고 싶어요. 가끔 그게 외롭기도 하지만, 가면을 쓰고 사는 것보다는 훨씬 나은 것 같아요.',
    postedAt: '2026-03-17T16:30:00',
    anonymousNickname: '맑은 이슬',
    liked: false,
    likeCount: 41,
    mine: false,
  },
  {
    answerPostId: 15,
    questionContent: '최근 마음이 따뜻해진 경험이 있나요?',
    description: null,
    answerContent: '편의점에서 계산할 때 카드가 안 됐는데, 뒤에 계신 아저씨가 "제가 할게요" 하면서 대신 결제해주셨어요. 금액은 작았지만, 낯선 사람의 친절이 하루 종일 마음을 따뜻하게 해줬어요.',
    postedAt: '2026-03-16T19:00:00',
    anonymousNickname: '기다리는 나무',
    liked: false,
    likeCount: 58,
    mine: false,
  },
  {
    answerPostId: 16,
    questionContent: '5년 전의 나와 지금의 나, 가장 큰 차이점은?',
    description: null,
    answerContent: '5년 전에는 남의 시선을 너무 신경 썼어요. 모든 결정을 "남들이 어떻게 생각할까"를 기준으로 했는데, 지금은 "내가 원하는 건 뭘까"를 먼저 물어봐요.',
    postedAt: '2026-03-16T11:30:00',
    anonymousNickname: '빛나는 별',
    liked: false,
    likeCount: 36,
    mine: false,
  },
  {
    answerPostId: 17,
    questionContent: '지금 내가 가장 필요한 것은?',
    description: null,
    answerContent: '충분한 휴식이요. 요즘 너무 바빠서 제대로 쉬지 못하고 있어요. 아무것도 하지 않아도 되는 온전한 하루가 필요해요.',
    postedAt: '2026-03-15T22:00:00',
    anonymousNickname: '잠드는 저녁',
    liked: false,
    likeCount: 29,
    mine: false,
  },
  {
    answerPostId: 18,
    questionContent: '가장 좋아하는 계절과 그 이유는?',
    description: null,
    answerContent: '가을이요. 덥지도 춥지도 않은 날씨, 알록달록한 나뭇잎, 그리고 어딘가 쓸쓸하면서도 아름다운 분위기가 좋아요.',
    postedAt: '2026-03-15T15:00:00',
    anonymousNickname: '춤추는 나비',
    liked: true,
    likeCount: 27,
    mine: false,
  },
  {
    answerPostId: 19,
    questionContent: '오늘 하루를 색깔로 표현한다면?',
    description: null,
    answerContent: '연한 주황색이요. 아침에 일찍 일어나서 조깅을 했는데, 해 뜨는 하늘이 정말 예뻤어요. 그 따뜻하고 부드러운 주황빛이 오늘 하루의 기분을 잘 표현해주는 것 같아요.',
    postedAt: '2026-03-14T20:00:00',
    anonymousNickname: '깨어나는 아침',
    liked: false,
    likeCount: 18,
    mine: false,
  },
  {
    answerPostId: 20,
    questionContent: '지금 옆에 있는 사람에게 하고 싶은 말은?',
    description: null,
    answerContent: '항상 곁에 있어줘서 고마워. 말로 자주 표현하지 못하지만, 네가 있어서 하루하루가 견딜 만해. 우리 앞으로도 서로에게 좋은 사람이 되자.',
    postedAt: '2026-03-14T18:30:00',
    anonymousNickname: '속삭이는 풀',
    liked: false,
    likeCount: 71,
    mine: false,
  },
];
